# Generated by Django 2.1.7 on 2020-05-02 11:36

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='unique id')),
                ('first_name', models.CharField(blank=True, default='', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('country_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Country Code In Phone Number')),
                ('address', models.CharField(blank=True, default='', max_length=150, verbose_name='Address')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'verbose_name': 'User',
            },
        ),
    ]
